[package]
name = "ironsnake-package2-pyo3"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module", "abi3-py38"]}
rand = "0.8.4"

[profile.release]
codegen-units = 1
lto = "fat"

[workspace]