[package]
name = "ironsnake-project1-pyo3"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19"

[dependencies.ironsnake]
path = "../../crates/ironsnake"
default-features = false

[profile.release]
codegen-units = 1
lto = "fat"

[workspace]
